-- =======================================
-- Každá zaminovaná oblast je vytvořená podle vlastní obtížnosti a
-- obsahuje její hodnoty. Hráč má za úkol oblast od min vyčistit.
--
-- @author Radek Vais
-- @version 23.3.2018
-- =======================================