-- =======================================
-- Každá hra musí mít definovanou obtížnost. Buď bude vybrána 
-- předdefinovaná, nebo si hráč definuje obtížnost vlastní. Hodnoty 
-- parametrů vlastní obtížnosti se ukládají do tabulky OBLAST. Podle 
-- originální hry jsou předdefinované obtížnosti nastaveny takto:
--    Začátečník: 9 řádků x 9 sloupců, 10 min
--    Pokročilý: 16 řádků x 16 sloupců, 40 min
--    Expert: 16 řádků x 30 sloupců, 99 min
--
-- @author Radek Vais
-- @version 23.3.2018
-- =======================================