-- =======================================
-- Script zaèistí databázové entity v DB
--
-- @author Radek Vais
-- @version 08.05.2018
-- =======================================

DROP PACKAGE MINESWEEPER_AUTOMATION;
DROP PACKAGE MINESWEEPER;

DROP TRIGGER TRIGGER_BI_SEM_HRA_ID;
DROP TRIGGER T_AD_SEM_MINA_REMOVED;
DROP TRIGGER T_AI_SEM_MINA_PLACED;
DROP TRIGGER T_AI_SEM_OBLAST;
DROP TRIGGER T_AI_SEM_TAH_PLAYED;
DROP TRIGGER T_BI_SEM_MINA_COUNT;
DROP TRIGGER T_BI_SEM_OBLAST;
DROP TRIGGER T_BI_SEM_OBLAST_ID;
DROP TRIGGER T_BI_SEM_OBLAST_PARAM;
DROP TRIGGER T_BI_SEM_POLE_ID;
DROP TRIGGER T_BI_SEM_TAH;
DROP TRIGGER T_BI_SEM_TAH_SHOWED;

DROP SEQUENCE SEQ_SEM_OBTIZNOST_ID;
DROP SEQUENCE SEQ_SEM_OBLAST_ID;
DROP SEQUENCE SEQ_SEM_POLE_ID;
DROP SEQUENCE SEQ_SEM_HRA_ID;

DROP TABLE SEM_HRA;
DROP TABLE SEM_TAH;
DROP TABLE SEM_MINA;
DROP TABLE SEM_POLE;
DROP TABLE SEM_OBLAST;
DROP TABLE SEM_STAV;
DROP TABLE SEM_OBTIZNOST;
DROP TABLE SEM_OMEZENI;

