DECLARE
BEGIN
   MINESWEEPER.VYTVOR_HRU(1);
END;

DECLARE
BEGIN
  MINESWEEPER.TAH(51, 1, 4 );
  MINESWEEPER.OBLAST_TISK(51);
END;

DECLARE
BEGIN
  MINESWEEPER.MINA(51, 9, 9 );
  MINESWEEPER.OBLAST_TISK(51);
END;

DECLARE
BEGIN
  MINESWEEPER.MINA(51, 8, 9 );
  MINESWEEPER.MINA(51, 7, 9 );
  MINESWEEPER.MINA(51, 6, 9 );
  MINESWEEPER.MINA(51, 5, 9 );
  MINESWEEPER.MINA(51, 4, 9 );
  MINESWEEPER.MINA(51, 3, 9 );
  MINESWEEPER.MINA(51, 2, 9 );
  MINESWEEPER.MINA(51, 1, 9 );
  MINESWEEPER.OBLAST_TISK(51);
END;

DECLARE
BEGIN
  MINESWEEPER.OBLAST_TISK(51);
END;

